export type MemoryType = 
  | 'fact'           // Simple facts, preferences
  | 'decision'       // Key decisions made
  | 'code'           // Code snippets, patterns
  | 'summary'        // Summarized content from pruning
  | 'project_context' // High-level project state
  | 'task'           // Specific task context
  | 'preference'     // User preferences
  | 'error'          // Errors and solutions
  | 'plan';          // Plans, roadmaps

export type MemorySource = 
  | 'user'           // User explicitly added
  | 'agent'          // Generated by agent
  | 'pruned'         // Auto-summarized from context
  | 'imported'       // Imported from external source
  | 'system';        // System-generated

export interface Memory {
  id: string;
  content: string;
  type: MemoryType;
  projectId?: string;
  source: MemorySource;
  priority: number;      // 0.0 - 1.0
  tokens?: number;
  embedding?: Uint8Array; // For future vector search
  createdAt: Date;
  updatedAt: Date;
  lastAccessed: Date;
  accessCount: number;
  isPinned: boolean;
  
  // NEW: Memory relationships and lifecycle
  ttlDays?: number;           // Time-to-live in days (null = eternal)
  expiresAt?: Date;           // Calculated expiration date
  updatesId?: string;         // ID of memory this supersedes
  relatedIds?: string[];      // IDs of related memories
  
  metadata?: Record<string, any>;
}

export interface CreateMemoryInput {
  content: string;
  type?: MemoryType;
  projectId?: string;
  source?: MemorySource;
  priority?: number;
  isPinned?: boolean;
  
  // NEW: Memory lifecycle
  ttlDays?: number;           // Auto-expire after N days
  updatesId?: string;         // This memory supersedes another
  relatedIds?: string[];      // Related memory IDs
  
  metadata?: Record<string, any>;
}

export interface UpdateMemoryInput {
  content?: string;
  type?: MemoryType;
  priority?: number;
  isPinned?: boolean;
  metadata?: Record<string, any>;
}

export interface MemorySearchOptions {
  projectId?: string;
  type?: MemoryType | MemoryType[];
  source?: MemorySource;
  query?: string;
  minPriority?: number;
  isPinned?: boolean;
  limit?: number;
  offset?: number;
  pinnedFirst?: boolean;
  recentFirst?: boolean;
}

export interface ContextWindow {
  sessionId: string;
  agentId?: string;
  projectId?: string;
  messages: any[];        // Message objects
  summary?: string;       // Summary of pruned content
  tokenUsed: number;
  tokenBudget: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateContextWindowInput {
  sessionId: string;
  agentId?: string;
  projectId?: string;
  messages: any[];
  tokenBudget?: number;
}

export interface Project {
  id: string;
  name: string;
  description?: string;
  status: 'active' | 'paused' | 'archived';
  workspacePath?: string;
  createdAt: Date;
  lastActivity: Date;
}

export interface CreateProjectInput {
  id?: string;
  name: string;
  description?: string;
  workspacePath?: string;
}
